# Generated by Django 4.1.3 on 2022-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=7588971907),
            preserve_default=False,
        ),
    ]
