# Generated by Django 4.1.3 on 2022-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopApp", "0002_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=None),
        ),
    ]
